### ISSUE TITLE
Add network check

### ISSUE THREAD

**Issue by mfbz** [rentfuse-labs/neo-wallet-adapter#10]
- To avoid invoking a contract and send accidentally real assets from the connected wallet, we need to add a network check
- From the docs, it can be leveraged the function getNetwork that is provided by all the supported wallets (Neoline and O3) and can be tweaked for walletconnect

**Comment by Mercurii7** [comment]
Hey @mfbz, I've attempted to add getNetworks (and signMessage) for Neoline and O3, but it probably won't work without removing/updating WalletConnect (I've removed it in my local build) as both new methods will be missing but required due to changes in WalletAdapterProps (or I should have set both methods to be optional?).

Perhaps we can merge/fix this after WalletConnect has been updated to use COZ's walletconnect-sdk.

**Comment by mfbz** [comment]
#18
